use_frameworks!

target 'ButtonSiteTool_Example' do
  pod 'ButtonSiteTool', :path => '../'

  target 'ButtonSiteTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
